# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=26.1.2
minecraft_version_range=[26.1,)
minecraft_support_version=26.1.x

# Forge
forge_id=forge
forge_version=52.1.10
forge_version_range=[52,)

mapping_channel=official
mapping_version=1.21.10

# NeoForge
neoforge_id=neoforge
neo_version=26.1.2.7-beta
neo_version_range=[26.1,)
neo_loader_version_range=[1,)

# Mod
mod_group_id=dev.xcolorful.customgun
mod_id=customgun
mod_name=Custom Gun Continued
mod_license=GPL-3.0-only
mod_version=0.0.4
mod_credits=Based on TaCZ and its contributors; continued by XiaoColorful
mod_authors=XiaoColorful
mod_description=A TaCZ derivative, keeping custom guns continued indefinitely

mod_issue_url=https://github.com/XColorful/Custom-Gun-Continued/issues
mod_display_url=https://github.com/XColorful/Custom-Gun-Continued/wiki
mod_logo_file=logo.png

pack_description=Custom Gun Continued resources
pack_format=15

# Mixin
mixin_config_file=customgun.mixins.json,customgunclient.mixins.json
mixin_config_file_forge=customgunforgeclient.mixins.json
mixin_config_file_neo=customgunneoforgeclient.mixins.json
mixin_annotation=org.spongepowered:mixin:0.8.5:processor
# MixinExtras (https://github.com/LlamaLad7/MixinExtras)
mixin_extras_version=0.5.4
mixin_extras_common=io.github.llamalad7:mixinextras-common
mixin_extras_annotation=io.github.llamalad7:mixinextras-common
mixin_extras_forge=io.github.llamalad7:mixinextras-forge

# Dependencies
luaj_figuramc_core=com.github.FiguraMC.luaj:luaj-core:3.0.8-figura
luaj_figuramc_jse=com.github.FiguraMC.luaj:luaj-jse:3.0.8-figura
luaj_figuramc_version=3.0.8
luaj_bcel=org.apache.bcel:bcel:6.6.1
luaj_bcel_version=6.6.1
apache_commons_math3=org.apache.commons:commons-math3:3.6.1
apache_commons_math3_version=3.6.1

# CompileOnly