# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.6
minecraft_version_range=[1.21.6,1.21.7)

# Forge
forge_id=forge
forge_version=52.1.10
forge_version_range=[52,)

mapping_channel=official
mapping_version=1.21.6

# NeoForge
neoforge_id=neoforge
neogradle.subsystems.parchment.minecraftVersion=1.21.6
neogradle.subsystems.parchment.mappingsVersion=2025.06.29
neo_version=21.6.20-beta
neo_version_range=[21,)
neo_loader_version_range=[1,)

# Mod
mod_group_id=xiao.customgun
mod_id=customgun
mod_name=Custom Gun Continued
mod_license=GPL-3.0 license
mod_version=0.0.0
mod_credits=XiaoColorful, XColorful
mod_authors=XiaoColorful
mod_description=

mod_issue_url=https://github.com/XColorful/Custom-Gun-Continued/issues
mod_display_url=https://github.com/XColorful/Custom-Gun-Continued/wiki
mod_logo_file=logo.png

pack_description=Custom Gun Continued resources
pack_format=15

# Dependencies

# CompileOnly