# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.21.2)

# Forge
forge_id=forge
forge_version=52.1.10
forge_version_range=[52,)

mapping_channel=official
mapping_version=1.21.1

# NeoForge
neoforge_id=neoforge
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neo_version=21.1.219
neo_version_range=[21,)
neo_loader_version_range=[1,)

# Mod
mod_group_id=xiao.customgun
mod_id=customgun
mod_name=Custom Gun Continued
mod_license=GPL-3.0-only
mod_version=0.0.0
mod_credits=Based on TaCZ and its contributors; continued by XiaoColorful
mod_authors=XiaoColorful
mod_description=A TaCZ derivative, keeping custom guns continued indefinitely

mod_issue_url=https://github.com/XColorful/Custom-Gun-Continued/issues
mod_display_url=https://github.com/XColorful/Custom-Gun-Continued/wiki
mod_logo_file=logo.png

pack_description=Custom Gun Continued resources
pack_format=15

# Mixin
mixin_config_file=customgun.mixins.json,customgunclient.mixins.json
mixin_annotation=org.spongepowered:mixin:0.8.5:processor
# MixinExtras (https://github.com/LlamaLad7/MixinExtras)
mixin_extras_version=0.5.4
mixin_extras_common=io.github.llamalad7:mixinextras-common
mixin_extras_annotation=io.github.llamalad7:mixinextras-common
mixin_extras_forge=io.github.llamalad7:mixinextras-forge

# Dependencies

# CompileOnly