pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'SpongePowered'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
        mavenLocal()
        maven { url = 'https://maven.neoforged.net/releases' }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.9.0'
}

sourceControl {
    gitRepository(URI.create("https://github.com/FiguraMC/luaj.git")) {
        producesModule("com.github.FiguraMC.luaj:luaj-jse-figura")
    }
    gitRepository(URI.create("https://github.com/FiguraMC/luaj.git")) {
        producesModule("com.github.FiguraMC.luaj:luaj-core-figura")
    }
}

include("core", "forge-compat")