plugins {
    id 'java-library'
    id 'net.neoforged.gradle.userdev' version '7.1.21'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    // MixinExtras
    compileOnly "${mixin_extras_common}:${mixin_extras_version}"
    annotationProcessor "${mixin_extras_common}:${mixin_extras_version}"

    // LuaJ
    compileOnly "${luaj_figuramc_core}"
    compileOnly "${luaj_figuramc_jse}"
    compileOnly "${luaj_bcel}"
}

jar {
    archiveBaseName.set(mod_id)
    archiveVersion.set(mod_version)
    archiveClassifier.set("core")
}