plugins {
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

minecraft {
    mappings channel: mapping_channel, version: mapping_version
    copyIdeResources = false
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
    compileOnly fg.deobf("net.minecraftforge:forge:${minecraft_version}-${forge_version}")

    // MixinExtras
    compileOnly "${mixin_extras_common}:${mixin_extras_version}"
    annotationProcessor "${mixin_extras_common}:${mixin_extras_version}"

    // LuaJ
    compileOnly "${luaj_figuramc_core}"
    compileOnly "${luaj_figuramc_jse}"
    compileOnly "${luaj_bcel}"
}

jar {
    archiveBaseName.set(mod_id)
    archiveVersion.set(mod_version)
    archiveClassifier.set("core")
}